# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: A
    steps:
      - bash: echo "Hi, I am Job A"
  - job: B
    dependsOn: A
    steps:
      - bash: echo "Hi, I am job B"