# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: A
        steps:
          - bash: echo "Hi , I am from Build Stage - Job A"
          - bash: echo "Job A Second Line"
        displayName: Job A
      - job: B
        steps:
          - bash: echo "Hi , I am from Build Stage - Job B"
  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: A
        steps:
          - bash: echo "Hi , I am from DevDeploy Stage - Job A"
      - job: B
        dependsOn: A
        steps:
          - bash: echo "Hi , I am from DevDeploy Stage - Job B"